Traceback (most recent call last):
  File "clear_ofc_log.py", line 30, in <module>
    res = requests.post(ofc_log_url, headers=headers, data=query_string)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.60.151', port=9200): Max retries exceeded with url: /ofc/ofc_log/_search?pretty (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fedfa70fc50>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
Traceback (most recent call last):
  File "clear_ofc_log.py", line 37, in <module>
    ofc_log_hits = ofc_log_obj['hits']['hits']
KeyError: 'hits'
